import scrapy
from scrapy.item import Item, Field

class DownloadedhotelsItem(scrapy.Item):
	h_name = Field()
	h_reviewnums = Field()
	h_ranking = Field()
	h_address1 = Field()
	h_address2 = Field()
	h_phone = Field()
	checkin_dates = Field()
	checkout_dates = Field()
	h_amenities1 = Field()
	h_amenities2 = Field()
	h_amenities3 = Field()
	h_amenities4 = Field()
	h_amenities5 = Field()
	h_amenities6 = Field()
	h_amenities7 = Field()
	h_starrating = Field()
	h_tripadvisor_rating = Field()
	h_rating_excellent = Field()
	h_rating_vgood = Field()
	h_rating_avg = Field()
	h_rating_poor = Field()
	h_rating_terrible = Field()
	h_review1 = Field()
	h_review2 = Field()
	h_review3 = Field()
	h_review4 = Field()
	h_review5 = Field()
	pass